/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all assets
         * @description One page of every stored asset, ordered by asset id unless `sort` says otherwise, optionally filtered by text (case-insensitive substring of the id or name), asset type and operational status. `total` counts all matches across pages.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Text to look for in the asset id or name */
                    q?: string;
                    /** @description Only assets of this type (see GET /api/lookups) */
                    type?: string;
                    /** @description Only assets in this operational status (see GET /api/lookups) */
                    status?: string;
                    /** @description Column to order by; ties and the default are by asset id. Assets with no parent sort last. */
                    sort?: "asset_id" | "name" | "type" | "status" | "parent";
                    /** @description Sort direction */
                    dir?: "asc" | "desc";
                    /** @description Page size */
                    limit?: number;
                    /** @description Rows to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.AssetListResponse"];
                    };
                };
                /** @description Unknown type, status or sort, or bad dir/limit/offset */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List top-level assets
         * @description Every asset that has no parent (substations), each with `child_count` and `subtree_count` so a tree can render expanders without further requests.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.RootsResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search assets
         * @description Case-insensitive substring match on asset id or name, optionally restricted to one asset type. Exact id matches come first, then id prefixes. `%` and `_` in `q` are matched literally. Results are capped at `limit`; `truncated` says whether more matched.
         */
        get: {
            parameters: {
                query: {
                    /** @description Text to look for in the asset id or name */
                    q: string;
                    /** @description Only assets of this type (see GET /api/lookups) */
                    type?: string;
                    /** @description Maximum results */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.SearchResponse"];
                    };
                };
                /** @description Missing q, unknown type, or bad limit */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Count assets by type and status
         * @description The total number of stored assets and how many there are of each asset type and each operational status. Types and statuses with no assets are omitted.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.StatsResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{assetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one asset
         * @description Every stored attribute of the asset.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Asset id
                     * @example TX-001-1
                     */
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.AssetDetail"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No such asset */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete one asset
         * @description Removes an asset that has no children. An asset that still has children is refused with 409 and must have them deleted first. See docs/KNOWN_LIMITATIONS.md.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Asset id
                     * @example TX-001-1
                     */
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No API key is configured on the server, so the API is disabled */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No such asset */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description The asset has children, or another writer collided with the delete */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{assetId}/ancestors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an asset's ancestor path
         * @description The path from the top of the hierarchy down to the asset, in that order; the asset itself is the last element. Use it to expand a tree to a search hit.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Asset id
                     * @example SWP-001-1-1
                     */
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.AncestorsResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No such asset */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{assetId}/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List an asset's children
         * @description The asset's immediate children grouped by asset type (each with `child_count` and `subtree_count`), plus `descendant_counts`: how many descendants of each type sit anywhere beneath the asset. An asset with no children returns empty lists.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Asset id
                     * @example SUB-001
                     */
                    assetId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ChildrenResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No such asset */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List past imports
         * @description One page of import activity, newest first: file name, client IP, row counts and whether data was committed. Imports only — deletions are not listed. Fetch `GET /api/imports/{importId}` for a run's rejected rows.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page size */
                    limit?: number;
                    /** @description Rows to skip */
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ImportListResponse"];
                    };
                };
                /** @description Bad limit or offset */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Import assets from a CSV file
         * @description Uploads a CSV of grid assets, validates every row again, and stores the rows that pass in one transaction. Rejected rows, and any row beneath a rejected parent, are skipped and reported; rows whose `asset_id` already exists are rejected, never updated. `committed` is true when at least one row was stored.
         *
         *     To let a user review the outcome first, call `POST /api/imports/preview` and send its `fingerprint` here as `expected_fingerprint`: if the file or the stored data changed since, nothing is written and the response is **412**. Without `expected_fingerprint` the rows that pass are stored directly.
         *
         *     **Columns are matched by header name**, in any order (case, spaces, `-` and `_` are ignored: `Asset ID` = `asset_id`). Required: `asset_id`, `asset_type`, `asset_name`, `operational_status`. Optional (may be absent from the file or blank): `parent_asset_id`, `voltage_kv`, `rating_kva`, `manufacturer`, `model`, `serial_number`, `commissioned_date` (`YYYY-MM-DD`, `D/M/YYYY` or `D/M/YY`, day first). Unknown columns are ignored and listed in `ignored_columns`. Allowed asset types, statuses and parent/child pairings are read from the database — see `GET /api/lookups`.
         *
         *     A file that is readable but has bad rows returns **200** with `rejections[]`; `csv_row` is the row's line in the uploaded file (header = line 1). A file that cannot be processed at all (not CSV, empty, required column missing) returns a 4xx `ErrorResponse` instead.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description CSV file with a header row
                         */
                        file: string;
                        /** @description Fingerprint from POST /api/imports/preview for this file */
                        expected_fingerprint?: string;
                    };
                };
            };
            responses: {
                /** @description Import outcome — check `committed`, `imported_rows` and `rejections` */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ImportResponse"];
                    };
                };
                /** @description No file supplied, or the file is empty / has no data rows */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Another writer changed the stored data during the commit; nothing was stored, retry */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description expected_fingerprint no longer matches; nothing was stored, preview again */
                412: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description File larger than the configured upload limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description File does not have a .csv extension */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Malformed CSV (see `line`), or the header lacks a required column */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unexpected error; quote `trace_id` when reporting */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check a CSV file without importing it
         * @description Validates the file exactly as `POST /api/imports` would and reports how many rows can be imported and which are rejected and why, **without storing anything** (no assets, no import record). Show this to the user, then confirm by sending the same file to `POST /api/imports` with `expected_fingerprint` set to the `fingerprint` returned here.
         *
         *     Column rules, date formats (`YYYY-MM-DD`, `D/M/YYYY`, `D/M/YY`, day first) and structural errors are the same as for the import.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description CSV file with a header row
                         */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Validation outcome; nothing was stored */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ImportPreviewResponse"];
                    };
                };
                /** @description No file supplied, or the file is empty / has no data rows */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description File larger than the configured upload limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description File does not have a .csv extension */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Malformed CSV (see `line`), or the header lacks a required column */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Unexpected error; quote `trace_id` when reporting */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download the import template
         * @description A CSV with every importable column in its header and a few fictional example rows (a small valid hierarchy) showing how parents, dates and statuses are written. Delete the example rows before importing your own data.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description asset_import_template.csv */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{importId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a past import
         * @description Re-fetches the result of an earlier import, including every rejected row. `ignored_columns` is only reported on the upload response and is empty here.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Import id (UUID) from POST /api/imports */
                    importId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ImportResponse"];
                    };
                };
                /** @description importId is not a UUID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description No such import */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lookups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reference data
         * @description The asset types, operational statuses and parent/child type pairings that imports are validated against, read from the database (refreshed on startup and on every import). Use it to build filters and dropdowns instead of hardcoding values.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.LookupsResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns service liveness and DB connectivity status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.HealthResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dto.HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "dto.AncestorsResponse": {
            /** @example SWP-001-1-1 */
            asset_id: string;
            path: components["schemas"]["dto.AssetSummary"][];
        };
        "dto.AssetDetail": {
            /** @example TX-001-1 */
            asset_id: string;
            /** @example Transformer 1 */
            asset_name: string;
            /** @example TRANSFORMER */
            asset_type: string;
            /**
             * @description CommissionedDate is formatted YYYY-MM-DD.
             * @example 2019-04-30
             */
            commissioned_date: string | null;
            /**
             * Format: date-time
             * @example 2026-09-20T08:15:00Z
             */
            created_at: string;
            /** @example ABB */
            manufacturer: string | null;
            /** @example RESIBLOC */
            model: string | null;
            /** @example IN_SERVICE */
            operational_status: string;
            /** @example SUB-001 */
            parent_asset_id: string | null;
            /** @example 1000 */
            rating_kva: number | null;
            /** @example SN-99812 */
            serial_number: string | null;
            /**
             * Format: date-time
             * @example 2026-09-20T08:15:00Z
             */
            updated_at: string;
            /** @example 22 */
            voltage_kv: number | null;
        };
        "dto.AssetListResponse": {
            items: components["schemas"]["dto.AssetSummary"][];
            /** @example 25 */
            limit: number;
            /** @example 0 */
            offset: number;
            /**
             * @description Total is the number of assets matching the filters, across all pages.
             * @example 206
             */
            total: number;
        };
        "dto.AssetNode": {
            /** @example SWB-001-1 */
            asset_id: string;
            /** @example Switchboard 1 */
            asset_name: string;
            /** @example SWITCHBOARD */
            asset_type: string;
            /**
             * @description ChildCount is the number of immediate children (0 = leaf).
             * @example 4
             */
            child_count: number;
            /** @example 2019-04-30 */
            commissioned_date: string | null;
            /** @example IN_SERVICE */
            operational_status: string;
            /** @example SUB-001 */
            parent_asset_id: string | null;
            /**
             * @description RatingKVA and CommissionedDate let a list of nodes (the children of an
             *     asset) be sorted without a request per row. CommissionedDate is YYYY-MM-DD.
             * @example 1000
             */
            rating_kva: number | null;
            /**
             * @description SubtreeCount is the number of assets in this asset's subtree,
             *     including the asset itself (a leaf has 1).
             * @example 5
             */
            subtree_count: number;
        };
        "dto.AssetSummary": {
            /** @example TX-001-1 */
            asset_id: string;
            /** @example Transformer 1 */
            asset_name: string;
            /** @example TRANSFORMER */
            asset_type: string;
            /** @example IN_SERVICE */
            operational_status: string;
            /** @example SUB-001 */
            parent_asset_id: string | null;
        };
        "dto.ChildGroup": {
            /** @example SWITCHBOARD */
            asset_type: string;
            assets: components["schemas"]["dto.AssetNode"][];
            /**
             * @description Count is the number of immediate children of this type.
             * @example 2
             */
            count: number;
            /**
             * @description SubtreeCount is the combined subtree size of those children
             *     (each child counted with its own descendants).
             * @example 9
             */
            subtree_count: number;
        };
        "dto.ChildrenResponse": {
            /** @example SUB-001 */
            asset_id: string;
            descendant_counts: components["schemas"]["dto.TypeCount"][];
            groups: components["schemas"]["dto.ChildGroup"][];
            /** @example 6 */
            total_children: number;
        };
        "dto.ErrorResponse": {
            /**
             * @description Error is a human-readable, user-safe message. For 5xx it is generic —
             *     internals are only ever written to the server log.
             * @example file "assets.txt" must have a .csv extension
             */
            error: string;
            /**
             * @description Line is the 1-indexed source line of a structurally malformed CSV, when known.
             * @example 42
             */
            line?: number;
            /**
             * @description TraceID matches the X-Trace-Id response header and the server log lines
             *     for this request; quote it when reporting a 5xx.
             * @example 7f6c1a52-3c1e-4a51-9d0b-5b1b2f7a9c11
             */
            trace_id?: string;
        };
        "dto.HealthResponse": {
            db: string;
            status: string;
        };
        "dto.ImportListResponse": {
            items: components["schemas"]["dto.ImportSummary"][];
            /** @example 25 */
            limit: number;
            /** @example 0 */
            offset: number;
            /** @example 3 */
            total: number;
        };
        "dto.ImportPreviewResponse": {
            /**
             * @description Fingerprint is a SHA-256 hex digest of the file's cells and of the
             *     validation outcome.
             * @example 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
             */
            fingerprint: string;
            /**
             * @description IgnoredColumns lists header columns the importer does not recognise.
             * @example [
             *       "legacy_ref",
             *       "notes"
             *     ]
             */
            ignored_columns: string[];
            /** @example 206 */
            importable_rows: number;
            /** @example 16 */
            rejected_rows: number;
            rejections: components["schemas"]["dto.Rejection"][];
            /** @example 222 */
            total_rows: number;
        };
        "dto.ImportResponse": {
            /** @example false */
            committed: boolean;
            /**
             * @description IgnoredColumns lists header columns the importer does not recognise;
             *     they are skipped (not an error) and not stored.
             * @example [
             *       "legacy_ref",
             *       "notes"
             *     ]
             */
            ignored_columns: string[];
            /**
             * Format: uuid
             * @example 0b5f3c7e-8a52-4a55-9b0e-0c9f8a3f6d11
             */
            import_id: string;
            /** @example 0 */
            imported_rows: number;
            /** @example 8 */
            rejected_rows: number;
            rejections: components["schemas"]["dto.Rejection"][];
            /** @example 222 */
            total_rows: number;
        };
        "dto.ImportSummary": {
            /** @example 203.0.113.7 */
            client_ip: string;
            /** @example true */
            committed: boolean;
            /**
             * Format: date-time
             * @example 2026-09-20T08:15:00Z
             */
            created_at: string;
            /** @example grid_assets.csv */
            filename: string;
            /**
             * Format: uuid
             * @example 0b5f3c7e-8a52-4a55-9b0e-0c9f8a3f6d11
             */
            import_id: string;
            /** @example 206 */
            imported_rows: number;
            /** @example 16 */
            rejected_rows: number;
            /** @example 222 */
            total_rows: number;
        };
        "dto.LookupsResponse": {
            /**
             * @example [
             *       "SUBSTATION",
             *       "TRANSFORMER"
             *     ]
             */
            asset_types: string[];
            /**
             * @example [
             *       "IN_SERVICE",
             *       "MAINTENANCE"
             *     ]
             */
            operational_statuses: string[];
            parent_rules: components["schemas"]["dto.ParentRule"][];
            /**
             * @description RootTypes are asset types with no parent rule: they must have no parent.
             * @example [
             *       "SUBSTATION"
             *     ]
             */
            root_types: string[];
        };
        "dto.ParentRule": {
            /** @example TRANSFORMER */
            child_type: string;
            /** @example SUBSTATION */
            parent_type: string;
        };
        "dto.Rejection": {
            /** @example TX-NR */
            asset_id: string;
            /**
             * @description CSVRow is the row's original 1-indexed line in the uploaded file
             *     (the header is line 1), not its position after any reordering.
             * @example 178
             */
            csv_row: number;
            /**
             * @description Reason holds every problem found on the row, joined with "; ".
             * @example rating_kva cannot be negative (-500)
             */
            reason: string;
        };
        "dto.RootsResponse": {
            roots: components["schemas"]["dto.AssetNode"][];
            /** @example 13 */
            total: number;
        };
        "dto.SearchResponse": {
            /** @example 2 */
            count: number;
            /** @example tx-001 */
            query: string;
            results: components["schemas"]["dto.AssetSummary"][];
            /**
             * @description Truncated is true when more assets matched than limit allowed.
             * @example false
             */
            truncated: boolean;
            /**
             * @description Type echoes the applied asset_type filter ("" = none).
             * @example TRANSFORMER
             */
            type: string;
        };
        "dto.StatsResponse": {
            by_status: components["schemas"]["dto.StatusCount"][];
            by_type: components["schemas"]["dto.TypeCount"][];
            /** @example 206 */
            total: number;
        };
        "dto.StatusCount": {
            /** @example 146 */
            count: number;
            /** @example IN_SERVICE */
            operational_status: string;
        };
        "dto.TypeCount": {
            /** @example TRANSFORMER */
            asset_type: string;
            /** @example 3 */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
